#pragma once
template<class T> class ArrayWrapper;
#include "../WrapperStructs.h"
#include ".././GameObject/PlayerReplicationInfoWrapper.h"
class GameEventWrapper;
class AirControlComponentWrapper;
class CarWrapper;

class BAKKESMOD_PLUGIN_IMPORT PriWrapper : public PlayerReplicationInfoWrapper {
public:
	CONSTRUCTORS(PriWrapper)

	//AUTO-GENERATED FROM FIELDS
	int GetMatchScore();
	void SetMatchScore(int newMatchScore);
	int GetMatchGoals();
	void SetMatchGoals(int newMatchGoals);
	int GetMatchOwnGoals();
	void SetMatchOwnGoals(int newMatchOwnGoals);
	int GetMatchAssists();
	void SetMatchAssists(int newMatchAssists);
	int GetMatchSaves();
	void SetMatchSaves(int newMatchSaves);
	int GetMatchShots();
	void SetMatchShots(int newMatchShots);
	int GetMatchDemolishes();
	void SetMatchDemolishes(int newMatchDemolishes);
	int GetMatchBonusXP();
	void SetMatchBonusXP(int newMatchBonusXP);
	int GetMatchBreakoutDamage();
	void SetMatchBreakoutDamage(int newMatchBreakoutDamage);
	unsigned long GetbMatchMVP();
	void SetbMatchMVP(unsigned long newbMatchMVP);
	unsigned long GetbMatchAdmin();
	void SetbMatchAdmin(unsigned long newbMatchAdmin);
	unsigned long GetbLoadoutSet();
	void SetbLoadoutSet(unsigned long newbLoadoutSet);
	unsigned long GetbOnlineLoadoutSet();
	void SetbOnlineLoadoutSet(unsigned long newbOnlineLoadoutSet);
	unsigned long GetbLoadoutsSet();
	void SetbLoadoutsSet(unsigned long newbLoadoutsSet);
	unsigned long GetbOnlineLoadoutsSet();
	void SetbOnlineLoadoutsSet(unsigned long newbOnlineLoadoutsSet);
	unsigned long GetbTeamPaintSet();
	void SetbTeamPaintSet(unsigned long newbTeamPaintSet);
	unsigned long GetbReady();
	void SetbReady(unsigned long newbReady);
	unsigned long GetbBusy();
	void SetbBusy(unsigned long newbBusy);
	unsigned long GetbUsingSecondaryCamera();
	void SetbUsingSecondaryCamera(unsigned long newbUsingSecondaryCamera);
	unsigned long GetbUsingBehindView();
	void SetbUsingBehindView(unsigned long newbUsingBehindView);
	unsigned long GetbUsingFreecam();
	void SetbUsingFreecam(unsigned long newbUsingFreecam);
	unsigned long GetbIsInSplitScreen();
	void SetbIsInSplitScreen(unsigned long newbIsInSplitScreen);
	unsigned long GetbDeveloper();
	void SetbDeveloper(unsigned long newbDeveloper);
	unsigned long GetbVoteToForfeitDisabled();
	void SetbVoteToForfeitDisabled(unsigned long newbVoteToForfeitDisabled);
	unsigned long GetbUsingItems();
	void SetbUsingItems(unsigned long newbUsingItems);
	unsigned long GetPlayerHistoryValid();
	void SetPlayerHistoryValid(unsigned long newPlayerHistoryValid);
	GameEventWrapper GetGameEvent();
	void SetGameEvent(GameEventWrapper newGameEvent);
	GameEventWrapper GetReplicatedGameEvent();
	void SetReplicatedGameEvent(GameEventWrapper newReplicatedGameEvent);
	CarWrapper GetCar();
	void SetCar(CarWrapper newCar);
	int GetRespawnTimeRemaining();
	void SetRespawnTimeRemaining(int newRespawnTimeRemaining);
	int GetWaitingStartTime();
	void SetWaitingStartTime(int newWaitingStartTime);
	float GetTotalGameTimePlayed();
	void SetTotalGameTimePlayed(float newTotalGameTimePlayed);
	unsigned char GetCameraPitch();
	void SetCameraPitch(unsigned char newCameraPitch);
	unsigned char GetCameraYaw();
	void SetCameraYaw(unsigned char newCameraYaw);
	unsigned char GetPawnType();
	void SetPawnType(unsigned char newPawnType);
	int GetTotalXP();
	void SetTotalXP(int newTotalXP);
	float GetDodgeInputThreshold();
	void SetDodgeInputThreshold(float newDodgeInputThreshold);
	float GetSteeringSensitivity();
	void SetSteeringSensitivity(float newSteeringSensitivity);
	float GetAirControlSensitivity();
	void SetAirControlSensitivity(float newAirControlSensitivity);
	float GetNextTimeRestrictedStatEventAllowedTime();
	void SetNextTimeRestrictedStatEventAllowedTime(float newNextTimeRestrictedStatEventAllowedTime);
	float GetLastTimeRestrictedStatEventTime();
	void SetLastTimeRestrictedStatEventTime(float newLastTimeRestrictedStatEventTime);
	int GetTimeTillItem();
	void SetTimeTillItem(int newTimeTillItem);
	int GetMaxTimeTillItem();
	void SetMaxTimeTillItem(int newMaxTimeTillItem);
	int GetBoostPickups();
	void SetBoostPickups(int newBoostPickups);
	int GetBallTouches();
	void SetBallTouches(int newBallTouches);
	int GetCarTouches();
	void SetCarTouches(int newCarTouches);
	PriWrapper GetReplacingBotPRI();
	void SetReplacingBotPRI(PriWrapper newReplacingBotPRI);

	//AUTO-GENERATED FUNCTION PROXIES
	void eventDestroyed();
	void OnUniqueIdChanged();
	void UpdatePlayerBanner();
	void BindCarDelegates(unsigned long bBind);
	void ClientUnlockAchievement(int AchievementId, unsigned char AchievementType);
	void UpdateCarLocalPlayer();
	void OnReplacingBotPRIChanged();
	void OnTeamChanged();
	void ClearBotReplacement();
	bool ValidateLoadoutTeamPaints();
	bool ValidateLoadoutSlots();
	void ValidateLoadoutDLC();
	void OnVoteToForfeitDisabled();
	void DisablebVoteToForfeit();
	void ServerVoteToForfeit();
	void SetUserCarPreferences(float NewDodgeThreshold, float NewSteeringSensitivity, float NewAirControlSensitivity);
	void ServerSetUserCarPreferences(float NewDodgeThreshold, float NewSteeringSensitivity, float NewAirControlSensitivity);
	void ServerSetTotalXP(int NewXP);
	void OnTotalXPChanged();
	void OnPawnTypeChanged();
	void SetWaitingPlayer(unsigned long B);
	void SetPawnType2(unsigned char NewPawnType);
	bool IsEditor();
	bool IsSpectator();
	void ServerSpectate();
	void ClientChangeTeamFailed(int TeamNum);
	void ServerChangeTeam(int TeamNum);
	void ReplicatePodiumTitles();
	void OnMatchAdmin();
	void OnMVPChange();
	void NotifyWonMVP();
	bool IsInvalidName();
	bool IsInWarmUpMode();
	void SetReady(unsigned long bNewReady);
	void ServerMatchAdminSetPaused(unsigned long bPause);
	void ServerMatchAdminSetScoreAndTime(int NewScoreTeam0, int NewScoreTeam1, int SecondsRemaining, unsigned long bOverTime, unsigned long bRestartRound);
	void SetMatchAdmin(unsigned long bIsMatchAdmin);
	void ServerReadyUp();
	bool ShouldBroadCastWelcomeMessage(unsigned long bExiting);
	void UpdateOnlineProductStats();
	void SetWaitingStartTime2();
	void OnRespawnTimeRemainingChanged();
	void SetRespawnTime2(int NewTime);
	void ClientScoredGoal(Vector& BallHitLocation);
	void OnRep_SteeringSensitivity();
	void OnRep_ClientScorePoint();
	void ResetScore();
	void RemovePoints(int Points);
	void ScorePoint2(int AdditionalScore);
	bool CanAwardTimeRestrictedStatEvent();
	void RecordTimeRestrictedStatEvent();
	void ResetTimeRestrictedStatEvent();
	void CommitStats();
	void UpdateFromLoadout();
	void UpdateUserCarPreferences(AirControlComponentWrapper AirControlComponent);
	void HandleAirControl(AirControlComponentWrapper AirControlComp);
	void SetCar2(CarWrapper NewCar);
	bool IsClientPlayerPRI();
	bool IsLocalPlayerPRI();
	void Unregister();
	void AddLocalPlayerToGameEvent();
	void OnLoadoutsSetInternal();
	bool AreLoadoutsSet();
	void OnLoadoutsOnlineSet();
	void OnLoadoutsSet2();
	bool ShouldValidateOnlineProducts();
	void OnSplitScreenStatusChanged();
	void ServerSplitScreenStatusChanged(unsigned long bInSplitScreen);
	void UpdateSplitScreenStatus();
	void OnPartyLeaderChanged();
	void UpdatePartyStatus();
	void OnSkillTierChanged();
	void ReplicateSkillTier(int NewTier);
	void OnTitleChanged();
	void UpdateTitle();
	void GetNewFriendKey();
	void ServerSetPlayerHistoryKey(unsigned char* HistoryKeyArray);
private:
	PIMPL
};